version: '3.7'

services:
    server:
        env_file: environment.env
        image: frontend_server
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        ports:
            - "8002:8000"
