version: '3.7'

services:
    server:
        env_file: environment.env
        image: warhouse_server
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        ports:
            - "8000:8000"
