version: '3.7'

services:
    server:
        env_file: environment.env
        image: users_server
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        ports:
            - "8001:8000"